### ISSUE TITLE
The active class is not being added

### ISSUE THREAD

**Issue by michaelwoodca** [Kail0/wp-materialize-navwalker#1]
I'm using the navwalker on WordPress 4.7 Vaughan and it's not adding the active class to the menu. 

`<?php wp_nav_menu( array( 'theme_location' => 'menu-1', 'container' => '', 'menu_id' => 'primary', 'menu_class' => 'right hide-on-med-and-down', 'walker' => new wp_materialize_navwalker() ) ); ?>`

**Comment by Kail0** [comment]
@HeliumVideo  I'll look into it.

**Comment by michaelwoodca** [comment]
Were you able to resolve it? @Kail0

**Comment by vitalized** [comment]
I'm also wondering if this has a fix?

**Comment by vitalized** [comment]
I'm also unable to see the 'active' class within the menu.

**Comment by conradolandia** [comment]
Bump. Also experiencing this issue.

**Comment by jimmycoate** [comment]
If it helps, I modified line 65 to read

`$output     .= $indent . '<li id="nav-menu-item-'. $item->ID . '" class="' . $depth_class_names . $class_names .'">';`

By including the $class_names variable, the active classes began working on the top level items for me.

**Comment by conradolandia** [comment]
I confirm that the solution provided by @jimmycoate works.

**Comment by jsgagne** [comment]
Same here. Thanks for the solution, @jimmycoate  !
