### ISSUE TITLE
Undefined variable: item_output 

### ISSUE THREAD

**Issue by arieltoledo** [Kail0/wp-materialize-navwalker#3]
Hi, im trying to use your walker. I followed the exact instructions of the reade but i got this error:

Undefined variable: item_output in /var/www/html/innovaonline/wp-content/themes/innovaclub/inc/wp_materialize_navwalker.php on line 84

**Comment by vitalized** [comment]
I'm getting the same error.  The menu works when debugging is turned off:
define('WP_DEBUG', false);

When debugging in 'true' I get an error: Undefined variable: item_output

**Comment by jonwaldstein** [comment]
It looks like the $item_output variable has just not been assigned previously.  I resolved this by adding `$item_output = $args->before;` right before `$item_output .= '<a'. $attributes .'>';`

**Comment by vitalized** [comment]
That's great!... Works with debugging 'true' now :-)
