### ISSUE TITLE
Materialize 1.0 Update?

### ISSUE THREAD

**Issue by schnoodly** [Kail0/wp-materialize-navwalker#8]
There are some updates that need to be done to the code, from side/mobile nav modifications, to the updates in Materialize code.

Is this project still in active management?

**Comment by Kail0** [comment]
Yup, I know. And I'm sorry for such a delay. I will look into all issues during holidays.

**Comment by Kail0** [comment]
I'm working on it, right now. Materialize 1.0 have changed a lot how javascript behave. And a lot of functions are deprecated.
I will try my best.
